<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.0							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.0">
<Header n="test9">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="test9">
<SecHeader>
  <MetricTable>
    <Metric i="34" n="REALTIME (usec):Sum (I)" v="derived-incr" t="inclusive" partner="35" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($34, $34)"/>
      <MetricFormula t="finalize" frm="$34"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="35" n="REALTIME (usec):Sum (E)" v="derived-incr" t="exclusive" partner="34" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($35, $35)"/>
      <MetricFormula t="finalize" frm="$35"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <TraceDBTable>
    <TraceDB i="0" db-glob="*.hpctrace" db-min-time="1472441363788050" db-max-time="1472441367117621" db-header-sz="32"/>
  </TraceDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/global/u2/h/hashim/GitLab/ALLVM/openMP_exp/build/test9"/>
  </LoadModuleTable>
  <FileTable>
    <File i="37077" n="./src/usr/include/unistd.h"/>
    <File i="37116" n="/usr/src/packages/BUILD/glibc-2.11.3/misc/../sysdeps/unix/sysv/linux/x86_64/syscall.S"/>
    <File i="57794" n="/usr/src/packages/BUILD/glibc-2.11.3/misc/../sysdeps/unix/sysv/linux/getsysstats.c"/>
    <File i="59136" n="/usr/src/packages/BUILD/glibc-2.11.3/nptl/../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S"/>
    <File i="59480" n="/usr/src/packages/BUILD/glibc-2.11.3/nptl/../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S"/>
    <File i="59744" n="/usr/src/packages/BUILD/glibc-2.11.3/nptl/../sysdeps/unix/syscall-template.S"/>
    <File i="63115" n="/usr/src/packages/BUILD/glibc-2.11.3/posix/../sysdeps/unix/syscall-template.S"/>
    <File i="63232" n="/usr/src/packages/BUILD/glibc-2.11.3/posix/../sysdeps/unix/sysv/linux/x86_64/sysconf.c"/>
    <File i="63239" n="../sysdeps/unix/sysv/linux/x86_64/sysconf.c"/>
    <File i="63265" n="../sysdeps/unix/sysv/linux/x86_64/../sysconf.c"/>
    <File i="63267" n="/usr/src/packages/BUILD/glibc-2.11.3/posix/../sysdeps/posix/sysconf.c"/>
    <File i="84484" n="kmp_affinity.o"/>
    <File i="85121" n="kmp_barrier.o"/>
    <File i="85810" n="kmp_runtime.o"/>
    <File i="92416" n="z_Linux_util.o"/>
    <File i="92526" n="~unknown-file~"/>
    <File i="92862" n=""/>
    <File i="93122" n=""/>
    <File i="93123" n=""/>
    <File i="94755" n=""/>
    <File i="94756" n=""/>
    <File i="95176" n=""/>
    <File i="95178" n=""/>
    <File i="95794" n="z_Linux_asm.o"/>
    <File i="95839" n=""/>
    <File i="95840" n=""/>
    <File i="95867" n=""/>
    <File i="95868" n=""/>
    <File i="95877" n=""/>
    <File i="97117" n=""/>
    <File i="99635" n=""/>
    <File i="99921" n=""/>
    <File i="99927" n=""/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="37114" n="syscall"/>
    <Procedure i="37116" n="syscall"/>
    <Procedure i="57795" n="next_line"/>
    <Procedure i="57829" n="__get_nprocs"/>
    <Procedure i="59137" n="pthread_cond_timedwait"/>
    <Procedure i="59138" n="__pthread_cond_timedwait"/>
    <Procedure i="59481" n="pthread_cond_wait"/>
    <Procedure i="59788" n="__read_nocancel"/>
    <Procedure i="63130" n="sched_yield"/>
    <Procedure i="63132" n="__sched_yield"/>
    <Procedure i="63233" n="__sysconf"/>
    <Procedure i="63239" n=""/>
    <Procedure i="63265" n="linux_sysconf"/>
    <Procedure i="63266" n=""/>
    <Procedure i="63267" n="posix_sysconf"/>
    <Procedure i="84784" n="__kmp_affinity_create_x2apicid_map(AddrUnsPair**, kmp_i18n_id*)"/>
    <Procedure i="84910" n="__kmp_aux_affinity_initialize()"/>
    <Procedure i="85178" n="__kmp_hyper_barrier_gather(barrier_type, kmp_info*, int, int, void (*)(void*, void*), void*)"/>
    <Procedure i="85192" n="__kmp_hyper_barrier_release(barrier_type, kmp_info*, int, int, int, void*)"/>
    <Procedure i="85855" n="__kmp_do_serial_initialize()"/>
    <Procedure i="92426" n="__kmp_launch_monitor(void*)"/>
    <Procedure i="92484" n="__kmp_launch_worker(void*)"/>
    <Procedure i="92532" n="___kmp_allocate"/>
    <Procedure i="92696" n="__kmp_affinity_bind_thread"/>
    <Procedure i="92744" n="__kmp_affinity_initialize"/>
    <Procedure i="92861" n="__kmp_allocate_team"/>
    <Procedure i="92931" n="__kmp_allocate_thread"/>
    <Procedure i="93119" n="__kmp_barrier"/>
    <Procedure i="93578" n="__kmp_determine_reduction_method"/>
    <Procedure i="94754" n="__kmp_external___intel_memset"/>
    <Procedure i="95152" n="__kmp_fork_barrier(int, int)"/>
    <Procedure i="95174" n="__kmp_fork_call"/>
    <Procedure i="95282" n="__kmp_get_global_thread_id_reg"/>
    <Procedure i="95461" n="__kmp_init_implicit_task"/>
    <Procedure i="95793" n="__kmp_invoke_microtask"/>
    <Procedure i="95794" n="L_kmp_invoke_pass_parms"/>
    <Procedure i="95797" n="L_kmp_invoke_push_parms"/>
    <Procedure i="95801" n="__kmp_invoke_task_func"/>
    <Procedure i="95836" n="__kmp_join_barrier(int)"/>
    <Procedure i="95862" n="__kmp_join_call"/>
    <Procedure i="95876" n="__kmp_launch_thread"/>
    <Procedure i="96036" n="__kmp_parallel_initialize"/>
    <Procedure i="96706" n="__kmp_release_ticket_lock"/>
    <Procedure i="96853" n="__kmp_runtime_initialize"/>
    <Procedure i="97115" n="__kmp_suspend_64"/>
    <Procedure i="97190" n="__kmp_task_team_sync"/>
    <Procedure i="97379" n="__kmp_yield"/>
    <Procedure i="99411" n="__kmpc_flush"/>
    <Procedure i="99416" n="__kmpc_for_static_init_4"/>
    <Procedure i="99436" n="__kmpc_fork_call"/>
    <Procedure i="99625" n="__kmpc_reduce_nowait"/>
    <Procedure i="99916" n="main"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<M n="34" v="5.50874e+07"/>
<PF i="2" s="92426" l="0" lm="2" f="92416" n="92426">
<M n="34" v="3.29034e+06"/>
<L i="3" s="92438" l="0" f="92416">
<M n="34" v="3.29034e+06"/>
<C i="4" s="92442" l="0">
<M n="34" v="3.29034e+06"/>
<PF i="5" s="59137" l="53" lm="2" f="59136" n="59137">
<M n="34" v="3.29034e+06"/><M n="35" v="3.29034e+06"/>
<Pr i="6" s="59138" l="53" lm="2" f="59136" n="59138" a="1">
<M n="34" v="3.29034e+06"/>
<S i="7" s="59139" l="53" it="209"/>
<L i="8" s="59174" l="273" f="59136">
<M n="34" v="3.29034e+06"/><M n="35" v="3.29034e+06"/>
<S i="9" s="59217" l="234">
<M n="34" v="3.29034e+06"/><M n="35" v="3.29034e+06"/>
</S>
</L>
</Pr>
</PF>
</C>
</L>
</PF>
<PF i="10" s="92484" l="0" lm="2" f="92416" n="92484">
<M n="34" v="4.84999e+07"/>
<C i="11" s="92499" l="0">
<M n="34" v="4.84999e+07"/>
<PF i="12" s="95876" l="0" lm="2" f="92526" n="95876">
<M n="34" v="4.84999e+07"/><M n="35" v="3004"/>
<L i="13" s="95877" l="0" f="95877">
<M n="34" v="4.84999e+07"/><M n="35" v="3004"/>
<S i="14" s="95878" l="0" it="4045">
<M n="34" v="3004"/><M n="35" v="3004"/>
</S>
<C i="15" s="95879" l="0">
<M n="34" v="741236"/>
<PF i="16" s="95152" l="0" lm="2" f="92526" n="95152">
<M n="34" v="741236"/>
<C i="17" s="95168" l="0">
<M n="34" v="739232"/>
<PF i="18" s="85192" l="0" lm="2" f="85121" n="85192">
<M n="34" v="739232"/><M n="35" v="536719"/>
<L i="19" s="85193" l="0" f="85121">
<M n="34" v="738229"/><M n="35" v="19023"/>
<C i="20" s="85194" l="0">
<M n="34" v="10019"/>
<PF i="21" s="97379" l="0" lm="2" f="92526" n="97379">
<M n="34" v="10019"/><M n="35" v="10019"/>
<S i="22" s="97380" l="0" it="3227">
<M n="34" v="10019"/><M n="35" v="10019"/>
</S>
</PF>
</C>
<S i="23" s="85194" l="0">
<M n="34" v="19023"/><M n="35" v="19023"/>
</S>
<C i="24" s="85195" l="0">
<M n="34" v="2003"/>
<PF i="25" s="63130" l="82" lm="2" f="63115" n="63130">
<M n="34" v="2003"/><M n="35" v="2003"/>
<Pr i="26" s="63132" l="82" lm="2" f="63115" n="63132" a="1">
<M n="34" v="2003"/><M n="35" v="2003"/>
<S i="27" s="63133" l="82" it="4013">
<M n="34" v="2003"/><M n="35" v="2003"/>
</S>
</Pr>
</PF>
</C>
<C i="28" s="85196" l="0">
<M n="34" v="189488"/>
<PF i="29" s="97115" l="0" lm="2" f="92526" n="97115">
<M n="34" v="189488"/>
<L i="30" s="97117" l="0" f="97117">
<M n="34" v="189488"/>
<C i="31" s="97119" l="0">
<M n="34" v="189488"/>
<PF i="32" s="59481" l="50" lm="2" f="59480" n="59481">
<M n="34" v="189488"/><M n="35" v="189488"/>
<S i="33" s="59482" l="50" it="231"/>
<L i="34" s="59534" l="274" f="59480">
<M n="34" v="189488"/><M n="35" v="189488"/>
<S i="35" s="59562" l="181">
<M n="34" v="189488"/><M n="35" v="189488"/>
</S>
</L>
</PF>
</C>
</L>
</PF>
</C>
<L i="36" s="85197" l="0" f="85121">
<M n="34" v="517696"/>
<L i="37" s="85198" l="0" f="85121">
<M n="34" v="517696"/><M n="35" v="517696"/>
<S i="38" s="85199" l="0" it="1585">
<M n="34" v="517696"/><M n="35" v="517696"/>
</S>
</L>
</L>
</L>
<C i="39" s="85205" l="0">
<M n="34" v="1003"/>
<PF i="40" s="95461" l="0" lm="2" f="92526" n="95461">
<M n="34" v="1003"/><M n="35" v="1003"/>
<S i="41" s="95462" l="0" it="4131">
<M n="34" v="1003"/><M n="35" v="1003"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="42" s="95170" l="0">
<M n="34" v="2004"/>
<PF i="43" s="97190" l="0" lm="2" f="92526" n="97190">
<M n="34" v="2004"/><M n="35" v="2004"/>
<S i="44" s="97191" l="0" it="2585">
<M n="34" v="2004"/><M n="35" v="2004"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="45" s="95883" l="0">
<M n="34" v="4.77106e+07"/>
<PF i="46" s="95801" l="0" lm="2" f="92526" n="95801">
<M n="34" v="4.77106e+07"/>
<C i="47" s="95804" l="0">
<M n="34" v="4.77106e+07"/>
<PF i="48" s="95793" l="0" lm="2" f="92526" n="95793">
<M n="34" v="4.77106e+07"/><M n="35" v="1002"/>
<Pr i="49" s="95794" l="0" lm="2" f="95794" n="95794" a="1">
<M n="34" v="4.77096e+07"/>
<C i="50" s="95796" l="0">
<M n="34" v="4.77096e+07"/>
<PF i="51" s="99916" l="0" lm="2" f="92526" n="99916">
<M n="34" v="4.77096e+07"/><M n="35" v="7.56234e+06"/>
<L i="52" s="99921" l="0" f="99921">
<M n="34" v="4.18393e+07"/>
<L i="53" s="99927" l="0" f="99927">
<M n="34" v="4.18393e+07"/><M n="35" v="7.56234e+06"/>
<S i="54" s="99928" l="0" it="1197">
<M n="34" v="7.56234e+06"/><M n="35" v="7.56234e+06"/>
</S>
<C i="55" s="99929" l="0">
<M n="34" v="1.70003e+07"/>
<PF i="56" s="99411" l="0" lm="2" f="92526" n="99411">
<M n="34" v="1.70003e+07"/><M n="35" v="1.70003e+07"/>
<S i="57" s="99412" l="0" it="1137">
<M n="34" v="1.70003e+07"/><M n="35" v="1.70003e+07"/>
</S>
</PF>
</C>
<C i="58" s="99930" l="0">
<M n="34" v="1.72766e+07"/>
<PF i="59" s="99411" l="0" lm="2" f="92526" n="99411">
<M n="34" v="1.72766e+07"/><M n="35" v="1.72766e+07"/>
<S i="60" s="99412" l="0" it="1241">
<M n="34" v="1.72766e+07"/><M n="35" v="1.72766e+07"/>
</S>
</PF>
</C>
</L>
</L>
<C i="61" s="99934" l="0">
<M n="34" v="7015"/>
<PF i="62" s="99416" l="0" lm="2" f="92526" n="99416">
<M n="34" v="7015"/><M n="35" v="7015"/>
<S i="63" s="99417" l="0" it="2379">
<M n="34" v="7015"/><M n="35" v="7015"/>
</S>
</PF>
</C>
<C i="64" s="99936" l="0">
<M n="34" v="5.8633e+06"/>
<PF i="65" s="99625" l="0" lm="2" f="92526" n="99625">
<M n="34" v="5.8633e+06"/><M n="35" v="5006"/>
<C i="66" s="99627" l="0">
<M n="34" v="4007"/>
<PF i="67" s="93578" l="0" lm="2" f="92526" n="93578">
<M n="34" v="4007"/><M n="35" v="4007"/>
<S i="68" s="93579" l="0" it="1267">
<M n="34" v="4007"/><M n="35" v="4007"/>
</S>
</PF>
</C>
<L i="69" s="99635" l="0" f="99635">
<M n="34" v="5006"/><M n="35" v="5006"/>
<S i="70" s="99636" l="0" it="1467">
<M n="34" v="5006"/><M n="35" v="5006"/>
</S>
</L>
<C i="71" s="99640" l="0">
<M n="34" v="5.85429e+06"/>
<PF i="72" s="93119" l="0" lm="2" f="92526" n="93119">
<M n="34" v="5.85429e+06"/><M n="35" v="4006"/>
<L i="73" s="93122" l="0" f="93122">
<M n="34" v="4006"/>
<L i="74" s="93123" l="0" f="93123">
<M n="34" v="4006"/><M n="35" v="4006"/>
<S i="75" s="93124" l="0" it="3179">
<M n="34" v="4006"/><M n="35" v="4006"/>
</S>
</L>
</L>
<C i="76" s="93150" l="0">
<M n="34" v="736947"/>
<PF i="77" s="85178" l="0" lm="2" f="85121" n="85178">
<M n="34" v="736947"/><M n="35" v="707906"/>
<L i="78" s="85179" l="0" f="85121">
<M n="34" v="736947"/>
<L i="79" s="85180" l="0" f="85121">
<M n="34" v="736947"/><M n="35" v="2002"/>
<L i="80" s="85181" l="0" f="85121">
<M n="34" v="724931"/><M n="35" v="705904"/>
<S i="81" s="85182" l="0" it="3017">
<M n="34" v="705904"/><M n="35" v="705904"/>
</S>
<C i="82" s="85183" l="0">
<M n="34" v="9012"/>
<PF i="83" s="97379" l="0" lm="2" f="92526" n="97379">
<M n="34" v="9012"/><M n="35" v="9012"/>
<S i="84" s="97380" l="0" it="313">
<M n="34" v="9012"/><M n="35" v="9012"/>
</S>
</PF>
</C>
<C i="85" s="85184" l="0">
<M n="34" v="10015"/>
<PF i="86" s="63130" l="82" lm="2" f="63115" n="63130">
<M n="34" v="10015"/><M n="35" v="10015"/>
<Pr i="87" s="63132" l="82" lm="2" f="63115" n="63132" a="1">
<M n="34" v="10015"/><M n="35" v="10015"/>
<S i="88" s="63133" l="82" it="2951">
<M n="34" v="10015"/><M n="35" v="10015"/>
</S>
</Pr>
</PF>
</C>
</L>
<C i="89" s="85188" l="0">
<M n="34" v="10014"/>
<PF i="90" s="99916" l="0" lm="2" f="92526" n="99916">
<M n="34" v="10014"/><M n="35" v="10014"/>
<L i="91" s="99921" l="0" f="99921">
<M n="34" v="10014"/>
<L i="92" s="99927" l="0" f="99927">
<M n="34" v="10014"/><M n="35" v="10014"/>
<S i="93" s="99928" l="0" it="3553">
<M n="34" v="10014"/><M n="35" v="10014"/>
</S>
</L>
</L>
</PF>
</C>
<S i="94" s="85188" l="0">
<M n="34" v="2002"/><M n="35" v="2002"/>
</S>
</L>
</L>
</PF>
</C>
<C i="95" s="93157" l="0">
<M n="34" v="5.11233e+06"/>
<PF i="96" s="85192" l="0" lm="2" f="85121" n="85192">
<M n="34" v="5.11233e+06"/><M n="35" v="4.87002e+06"/>
<L i="97" s="85193" l="0" f="85121">
<M n="34" v="5.11233e+06"/><M n="35" v="187228"/>
<C i="98" s="85194" l="0">
<M n="34" v="102127"/>
<PF i="99" s="97379" l="0" lm="2" f="92526" n="97379">
<M n="34" v="102127"/><M n="35" v="102127"/>
<S i="100" s="97380" l="0" it="2983">
<M n="34" v="102127"/><M n="35" v="102127"/>
</S>
</PF>
</C>
<S i="101" s="85194" l="0">
<M n="34" v="187228"/><M n="35" v="187228"/>
</S>
<C i="102" s="85195" l="0">
<M n="34" v="140188"/>
<PF i="103" s="63130" l="82" lm="2" f="63115" n="63130">
<M n="34" v="135183"/><M n="35" v="135183"/>
<Pr i="104" s="63132" l="82" lm="2" f="63115" n="63132" a="1">
<M n="34" v="135183"/><M n="35" v="135183"/>
<S i="105" s="63133" l="82" it="2017">
<M n="34" v="135183"/><M n="35" v="135183"/>
</S>
</Pr>
</PF>
<PF i="106" s="97379" l="0" lm="2" f="92526" n="97379">
<M n="34" v="5005"/><M n="35" v="5005"/>
<S i="107" s="97380" l="0" it="3383">
<M n="34" v="5005"/><M n="35" v="5005"/>
</S>
</PF>
</C>
<L i="108" s="85197" l="0" f="85121">
<M n="34" v="4.68279e+06"/>
<L i="109" s="85198" l="0" f="85121">
<M n="34" v="4.68279e+06"/><M n="35" v="4.68279e+06"/>
<S i="110" s="85199" l="0" it="343">
<M n="34" v="4.68279e+06"/><M n="35" v="4.68279e+06"/>
</S>
</L>
</L>
</L>
</PF>
</C>
<C i="111" s="93158" l="0">
<M n="34" v="1002"/>
<PF i="112" s="97190" l="0" lm="2" f="92526" n="97190">
<M n="34" v="1002"/><M n="35" v="1002"/>
<S i="113" s="97191" l="0" it="3247">
<M n="34" v="1002"/><M n="35" v="1002"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</Pr>
<Pr i="114" s="95797" l="0" lm="2" f="95794" n="95797" a="1">
<M n="34" v="1002"/>
<L i="115" s="95798" l="0" f="95794">
<M n="34" v="1002"/><M n="35" v="1002"/>
<S i="116" s="95799" l="0">
<M n="34" v="1002"/><M n="35" v="1002"/>
</S>
</L>
</Pr>
<S i="117" s="95800" l="0" it="2971"/>
</PF>
</C>
</PF>
</C>
<C i="118" s="95885" l="0">
<M n="34" v="45069"/>
<PF i="119" s="95836" l="0" lm="2" f="92526" n="95836">
<M n="34" v="45069"/><M n="35" v="3006"/>
<L i="120" s="95839" l="0" f="95839">
<M n="34" v="3006"/>
<L i="121" s="95840" l="0" f="95840">
<M n="34" v="3006"/><M n="35" v="3006"/>
<S i="122" s="95841" l="0" it="3901">
<M n="34" v="3006"/><M n="35" v="3006"/>
</S>
</L>
</L>
<C i="123" s="95859" l="0">
<M n="34" v="42063"/>
<PF i="124" s="85178" l="0" lm="2" f="85121" n="85178">
<M n="34" v="42063"/><M n="35" v="42063"/>
<L i="125" s="85179" l="0" f="85121">
<M n="34" v="42063"/>
<L i="126" s="85180" l="0" f="85121">
<M n="34" v="42063"/>
<L i="127" s="85181" l="0" f="85121">
<M n="34" v="42063"/><M n="35" v="42063"/>
<S i="128" s="85182" l="0" it="3775">
<M n="34" v="42063"/><M n="35" v="42063"/>
</S>
</L>
</L>
</L>
</PF>
</C>
</PF>
</C>
</L>
</PF>
</C>
</PF>
<PF i="129" s="99916" l="0" lm="2" f="92526" n="99916">
<M n="34" v="3.29716e+06"/>
<C i="130" s="99919" l="0">
<M n="34" v="3926"/>
<PF i="131" s="95282" l="0" lm="2" f="92526" n="95282">
<M n="34" v="3926"/>
<C i="132" s="95293" l="0">
<M n="34" v="3926"/>
<PF i="133" s="85855" l="0" lm="2" f="85810" n="85855">
<M n="34" v="3926"/>
<C i="134" s="85901" l="0">
<M n="34" v="3926"/>
<PF i="135" s="96853" l="0" lm="2" f="92526" n="96853">
<M n="34" v="3926"/>
<C i="136" s="96856" l="0">
<M n="34" v="3926"/>
<PF i="137" s="63233" l="33" lm="2" f="63232" n="63233">
<M n="34" v="3926"/>
<Pr i="138" s="63239" l="37" lm="2" f="63239" n="63239" a="1">
<M n="34" v="3926"/>
<Pr i="139" s="63265" l="136" lm="2" f="63265" n="63265" a="1">
<M n="34" v="3926"/>
<Pr i="140" s="63266" l="136" lm="2" f="63265" n="63266" a="1">
<M n="34" v="3926"/>
<Pr i="141" s="63267" l="54" lm="2" f="63267" n="63267" a="1">
<M n="34" v="3926"/>
<C i="142" s="63283" l="631">
<M n="34" v="3926"/>
<PF i="143" s="57829" l="130" lm="2" f="57794" n="57829">
<M n="34" v="3926"/>
<L i="144" s="57842" l="158" f="57794">
<M n="34" v="3926"/>
<C i="145" s="57844" l="152">
<M n="34" v="3926"/>
<PF i="146" s="57795" l="78" lm="2" f="57794" n="57795">
<M n="34" v="3926"/>
<C i="147" s="57808" l="91">
<M n="34" v="3926"/>
<PF i="148" s="59788" l="82" lm="2" f="59744" n="59788">
<M n="34" v="3926"/><M n="35" v="3926"/>
<S i="149" s="59790" l="82" it="37">
<M n="34" v="3926"/><M n="35" v="3926"/>
</S>
</PF>
</C>
</PF>
</C>
</L>
</PF>
</C>
</Pr>
</Pr>
</Pr>
</Pr>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<L i="150" s="99921" l="0" f="99921">
<M n="34" v="3.29324e+06"/>
<C i="151" s="99923" l="0">
<M n="34" v="3.29324e+06"/>
<PF i="152" s="99436" l="0" lm="2" f="92526" n="99436">
<M n="34" v="3.29324e+06"/><M n="35" v="5010"/>
<S i="153" s="99437" l="0" it="3187">
<M n="34" v="5010"/><M n="35" v="5010"/>
</S>
<C i="154" s="99439" l="0">
<M n="34" v="3.26118e+06"/>
<PF i="155" s="95174" l="0" lm="2" f="92526" n="95174">
<M n="34" v="3.26118e+06"/><M n="35" v="7014"/>
<L i="156" s="95176" l="0" f="95176">
<M n="34" v="7014"/>
<L i="157" s="95178" l="0" f="95178">
<M n="34" v="7014"/><M n="35" v="7014"/>
<S i="158" s="95179" l="0" it="1697">
<M n="34" v="7014"/><M n="35" v="7014"/>
</S>
</L>
</L>
<C i="159" s="95207" l="0">
<M n="34" v="1002"/>
<PF i="160" s="96706" l="0" lm="2" f="92526" n="96706">
<M n="34" v="1002"/><M n="35" v="1002"/>
<S i="161" s="96707" l="0" it="3047">
<M n="34" v="1002"/><M n="35" v="1002"/>
</S>
</PF>
</C>
<C i="162" s="95210" l="0">
<M n="34" v="5007"/>
<PF i="163" s="95152" l="0" lm="2" f="92526" n="95152">
<M n="34" v="5007"/>
<C i="164" s="95168" l="0">
<M n="34" v="5007"/>
<PF i="165" s="85192" l="0" lm="2" f="85121" n="85192">
<M n="34" v="5007"/><M n="35" v="5007"/>
<L i="166" s="85193" l="0" f="85121">
<M n="34" v="5007"/>
<L i="167" s="85197" l="0" f="85121">
<M n="34" v="5007"/>
<L i="168" s="85198" l="0" f="85121">
<M n="34" v="5007"/><M n="35" v="5007"/>
<S i="169" s="85199" l="0" it="1963">
<M n="34" v="5007"/><M n="35" v="5007"/>
</S>
</L>
</L>
</L>
</PF>
</C>
</PF>
</C>
<C i="170" s="95211" l="0">
<M n="34" v="3.24511e+06"/>
<PF i="171" s="95801" l="0" lm="2" f="92526" n="95801">
<M n="34" v="3.24511e+06"/>
<C i="172" s="95804" l="0">
<M n="34" v="3.24511e+06"/>
<PF i="173" s="95793" l="0" lm="2" f="92526" n="95793">
<M n="34" v="3.24511e+06"/>
<Pr i="174" s="95794" l="0" lm="2" f="95794" n="95794" a="1">
<M n="34" v="3.24511e+06"/>
<C i="175" s="95796" l="0">
<M n="34" v="3.24511e+06"/>
<PF i="176" s="99916" l="0" lm="2" f="92526" n="99916">
<M n="34" v="3.24511e+06"/><M n="35" v="510797"/>
<L i="177" s="99921" l="0" f="99921">
<M n="34" v="3.01874e+06"/>
<L i="178" s="99927" l="0" f="99927">
<M n="34" v="3.01874e+06"/><M n="35" v="510797"/>
<S i="179" s="99928" l="0" it="1219">
<M n="34" v="510797"/><M n="35" v="510797"/>
</S>
<C i="180" s="99929" l="0">
<M n="34" v="1.22594e+06"/>
<PF i="181" s="99411" l="0" lm="2" f="92526" n="99411">
<M n="34" v="1.22594e+06"/><M n="35" v="1.22594e+06"/>
<S i="182" s="99412" l="0" it="1081">
<M n="34" v="1.22594e+06"/><M n="35" v="1.22594e+06"/>
</S>
</PF>
</C>
<C i="183" s="99930" l="0">
<M n="34" v="1.282e+06"/>
<PF i="184" s="99411" l="0" lm="2" f="92526" n="99411">
<M n="34" v="1.282e+06"/><M n="35" v="1.282e+06"/>
<S i="185" s="99412" l="0" it="1163">
<M n="34" v="1.282e+06"/><M n="35" v="1.282e+06"/>
</S>
</PF>
</C>
</L>
</L>
<C i="186" s="99934" l="0">
<M n="34" v="4008"/>
<PF i="187" s="99416" l="0" lm="2" f="92526" n="99416">
<M n="34" v="4008"/><M n="35" v="4008"/>
<S i="188" s="99417" l="0" it="1633">
<M n="34" v="4008"/><M n="35" v="4008"/>
</S>
</PF>
</C>
<C i="189" s="99936" l="0">
<M n="34" v="222361"/>
<PF i="190" s="99625" l="0" lm="2" f="92526" n="99625">
<M n="34" v="222361"/>
<C i="191" s="99640" l="0">
<M n="34" v="222361"/>
<PF i="192" s="93119" l="0" lm="2" f="92526" n="93119">
<M n="34" v="222361"/><M n="35" v="2004"/>
<L i="193" s="93122" l="0" f="93122">
<M n="34" v="1002"/>
<L i="194" s="93123" l="0" f="93123">
<M n="34" v="1002"/><M n="35" v="1002"/>
<S i="195" s="93124" l="0" it="3377">
<M n="34" v="1002"/><M n="35" v="1002"/>
</S>
</L>
</L>
<C i="196" s="93150" l="0">
<M n="34" v="217351"/>
<PF i="197" s="85178" l="0" lm="2" f="85121" n="85178">
<M n="34" v="217351"/><M n="35" v="213345"/>
<L i="198" s="85179" l="0" f="85121">
<M n="34" v="217351"/>
<L i="199" s="85180" l="0" f="85121">
<M n="34" v="217351"/>
<L i="200" s="85181" l="0" f="85121">
<M n="34" v="216350"/><M n="35" v="213345"/>
<S i="201" s="85182" l="0" it="193">
<M n="34" v="213345"/><M n="35" v="213345"/>
</S>
<C i="202" s="85183" l="0">
<M n="34" v="3005"/>
<PF i="203" s="97379" l="0" lm="2" f="92526" n="97379">
<M n="34" v="3005"/><M n="35" v="3005"/>
<S i="204" s="97380" l="0" it="631">
<M n="34" v="3005"/><M n="35" v="3005"/>
</S>
</PF>
</C>
</L>
<C i="205" s="85188" l="0">
<M n="34" v="1001"/>
<PF i="206" s="99916" l="0" lm="2" f="92526" n="99916">
<M n="34" v="1001"/><M n="35" v="1001"/>
<L i="207" s="99921" l="0" f="99921">
<M n="34" v="1001"/>
<L i="208" s="99927" l="0" f="99927">
<M n="34" v="1001"/><M n="35" v="1001"/>
<S i="209" s="99928" l="0" it="4081">
<M n="34" v="1001"/><M n="35" v="1001"/>
</S>
</L>
</L>
</PF>
</C>
</L>
</L>
</PF>
</C>
<C i="210" s="93157" l="0">
<M n="34" v="3006"/>
<PF i="211" s="85192" l="0" lm="2" f="85121" n="85192">
<M n="34" v="3006"/><M n="35" v="3006"/>
<L i="212" s="85193" l="0" f="85121">
<M n="34" v="3006"/>
<L i="213" s="85197" l="0" f="85121">
<M n="34" v="3006"/>